###
// Get user list
GET http://localhost:5000/user

###

GET http://localhost:5000/user/66c4a1c5d55c32b84c665476

###


DELETE http://localhost:5000/user/66bc69591c20e378209295af

###

POST http://localhost:5000/user
Content-Type: application/json

{
    "username": "bby",
    "password": "12",
    "email": "bby@nah.com"
}

###

POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "abs",
    "password": "12"
}




###

PATCH http://localhost:5000/user/66bc69591c20e378209295af
Content-Type: application/json

{
    "username": "abl"
}

###

GET http://localhost:5000/events
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmI2ZmQwOWZmYjIxMzdjYmYzZTdkZCIsImlhdCI6MTcyNDE2MjU4N30.rJK-2Mhz9RcAEegt8wSa4E5hhMB4M0ZcNlPq693c2WU