###
// Get user list
GET http://localhost:5000/user

###

GET http://localhost:5000/user/66c4a1c5d55c32b84c665476

###


DELETE http://localhost:5000/user/66bc69591c20e378209295af

###

POST http://localhost:5000/user
Content-Type: application/json

{
    "username": "peg",
    "password": "12",
    "email": "pegyz@nah.com"
}

###

POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "peg",
    "password": "12"
}




###

PATCH http://localhost:5000/user/66bc69591c20e378209295af
Content-Type: application/json

{
    "username": "abl"
}

###

GET http://localhost:5000/events
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzRhMWM1ZDU1YzMyYjg0YzY2NTQ3NiIsImlhdCI6MTcyNDE4OTczMX0.T7aZ6BV2hcrdYlGbuATB9pwpBnBHIGUQfeQdiNDPPE0

###

GET http://localhost:5000/events/home
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzUxN2ZmNzFkNGVlM2M0OWY0MDg5MSIsImlhdCI6MTcyNDE5MjgyMn0.qfaFS0Mxf8Q2HayLRVhTj3U2eVMHpV05WkWkXGkgo-Y