###
// Add a new user note
POST http://localhost:5000/notes/new
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDAwYzYzOTBkOTM2OWVhYjM1NjQ0ZiIsImlhdCI6MTcyODA1NjQxOX0.zLqMIe09Uuz1OXvceBTZxeMxlCKpfi2tUbHGwIimT_A
Content-Type: application/json

{
    "title": "my 3 note",
    "content": "lorem ipsum dolor sit ksjsjjs ijebnkjwbndkdwc cidwcikbdnwck amet"
}

###

// Get all user notes
GET http://localhost:5000/notes/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDAwYzYzOTBkOTM2OWVhYjM1NjQ0ZiIsImlhdCI6MTcyODA1NjQxOX0.zLqMIe09Uuz1OXvceBTZxeMxlCKpfi2tUbHGwIimT_A

###

// Delete a user note
DELETE http://localhost:5000/notes/delete/672779911f78715a7c1fb3de
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDAwYzYzOTBkOTM2OWVhYjM1NjQ0ZiIsImlhdCI6MTcyODA1NjQxOX0.zLqMIe09Uuz1OXvceBTZxeMxlCKpfi2tUbHGwIimT_A

###

// Update a user note
PUT http://localhost:5000/notes/update/67000d1e90d9369eab356465
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Yzc2NzM1ZDI2MWJmNjYyYjExMGMxZCIsImlhdCI6MTcyNDM0NDI0OH0.GisOaxci_bIVT1tQqArwwFsj7Sk7VHDkQnQ2kcsbPGs
Content-Type: application/json

{
    "content": "jingle bells jingle bells jingle all the way oh what fun it is to ride in a one horse open sleigh"
}